name: Generate CustomCar

on:
  workflow_dispatch:
    inputs:
      payload:
        description: 'JSON payload with model parameters'
        required: true
        type: string

jobs:
  generate:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET Framework
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '4.8'
    
    - name: Build Core
      run: |
        dotnet build Core/CustomCarExporter.Core.csproj -c Release
    
    - name: Build Generator
      run: |
        dotnet build Generator/Generator.csproj -c Release
    
    - name: Generate CustomCar
      run: |
        $payload = "${{ github.event.inputs.payload }}"
        $payload | Out-File -FilePath input.json -Encoding UTF8
        $output = "output.customcar"
        .\Generator\bin\Release\net48\Generator.exe input.json $output
    
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: customcar_file
        path: output.customcar
        retention-days: 7

